# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Roulette simulator
author: Ana Marija Atanasovska & Alek Jarmov
copyright: "2023"
logo: logo.png

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/alekjarmov/roulette-simulator/  # Online location of your book
  path_to_book: simulator_code  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

execute:
  execute_notebooks: 'off'
  
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
